nsi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^', include('employees.urls', namespace='employees')),
    url(r'^security/', include('security.urls', namespace='security')),
    url(r'^admin/', admin.site.urls),

    # Shared Application
    url(r'^shared/', include('shared.urls', namespace='shared')),

    # url(r'^404/$', TemplateView.as_view(template_name='404.html',)),
    # url(r'^500/$', TemplateView.as_view(template_name='500.html',)),
]

security/urls.py
from django.conf import settings
from django.conf.urls import patterns, url


urlpatterns = patterns('security.views',
    url(r'^login/$', 'login_form', name='login'),
    url(r'^logout/$', 'user_logout', name='logout'),
    url(r'^password/reset/$', 'reset_password', name='reset_password'),
    url(r'^password/create/{uuid_pattern}/{uuid_pattern}/$'.format(uuid_pattern=settings.UUID_PATTERN_REGEX), 'create_new_password',
        name='create_new_password'),
    url(r'^team/members/$', 'team_members', name='team_members'),
    url(r'^team/member/{}/$'.format(settings.UUID_PATTERN_REGEX), 'team_members', name='edit_team_member')

)

shared/urls.py
from django.conf import settings
from django.conf.urls import patterns, url


urlpatterns = patterns('shared.views',
)

shared/models.py
from sorl.thumbnail import ImageField, get_thumbnail

from django.conf import settings
from django.db import models


from security.models import CustomUser
from shared.utilities import make_uuid


class CommonFields(models.Model):
    is_active = models.BooleanField(default=True)
    dt_updated = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        abstract = True


class FunctionalCapability(CommonFields):
    capability_uuid = models.CharField(max_length=36, default=make_uuid, db_index=True)
    title = models.CharField(max_length=250, verbose_name='title of functional capability')
    text = models.TextField(verbose_name='detail')

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class TaskOrder(CommonFields):
    task_uuid = models.CharField(max_length=36, default=make_uuid, db_index=True)
    task_number = models.CharField(max_length=100)
    document = models.FileField(upload_to='{}/shared/static/documents'.format(settings.SITE_ROOT))

    class Meta:
        ordering = ['task_number']

    def __str__(self):
        return self.task_number

    @property
    def get_document_name(self):
        return self.document.url.split('/')[-1]


class NewsItem(CommonFields):
    news_uuid = models.CharField(max_length=36, default=make_uuid, db_index=True)
    featured = models.BooleanField(default=False, verbose_name='is this featured')
    title = models.CharField(max_length=250, verbose_name='title of news item')
    text = models.TextField(verbose_name='news detail')
    news_year = models.IntegerField()

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_item_year(self):
        return self.dt_updated.year


class ImageItem(CommonFields):
    image_uuid = models.CharField(max_length=36, default=make_uuid, db_index=True)
    title = models.CharField(max_length=250, verbose_name='title of image item')
    text = models.TextField(verbose_name='image detail', blank=True, null=True)
    featured = models.BooleanField(default=True, verbose_name='is this a featured image')
    image = models.ImageField(upload_to='{}/shared/static/img/slides'.format(settings.SITE_ROOT))

    def __str__(self):
        return self.title

    @property
    def get_image_name(self):
        return self.image.url.split('/')[-1]

    def get_thumbnail(self):
        return get_thumbnail(self.image, '555x350', quality=99)


class ContactItem(models.Model):
    contact_uuid = models.CharField(max_length=36, default=make_uuid, db_index=True)
    name = models.CharField(max_length=100, verbose_name='Name')
    email = models.EmailField(max_length=250, db_index=True)
    message = models.TextField(blank=True, null=True)
    category = models.CharField(max_length=30)
    dt_updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category


class FormCategory(CommonFields):
    category_uuid = models.CharField(max_length=36, default=make_uuid, db_index=True)
    category = models.CharField(max_length=250, verbose_name='form category')

    class Meta:
        ordering = ['category']

    def __str__(self):
        return self.category

    @property
    def get_my_forms(self):
        return self.formdata_set.all()

    def has_links_or_documents(self):
        form_data = self.get_my_forms

        return {
            'documents': form_data.filter(document__isnull=False),
            'links': form_data.filter(link__isnull=False)
        }


class FormData(CommonFields):
    form_uuid = models.CharField(max_length=36, default=make_uuid, db_index=True)
    title = models.CharField(max_length=250, verbose_name='title of form')
    text = models.TextField(verbose_name='form detail', blank=True, null=True)
    data_type = models.CharField(max_length=5)
    document = models.FileField(upload_to='{}/shared/static/forms'.format(settings.SITE_ROOT), blank=True, null=True)
    link = models.URLField(verbose_name='url to website', blank=True, null=True)
    category = models.ManyToManyField(FormCategory)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    @property
    def get_document_name(self):
        return self.document.url.split('/')[-1] if self.document else None

shared/forms.py
from django import forms
from django.utils.safestring import mark_safe
from django.utils.encoding import force_text
from django.utils.html import conditional_escape


class RadioSelectInline(forms.RadioSelect):
    def render(self, *args, **kwargs):
        output = super(RadioSelectInline, self).render(*args, **kwargs)
        return mark_safe(output.replace(u'<ul', u'<ul class="unstyled" ').replace(u'<li>', u'').replace(u'</li>', u'').replace(u'<label ', u'<label class="radio inline" '))


class CheckboxSelectInline(forms.CheckboxSelectMultiple):
    def render(self, *args, **kwargs):
        output = super(CheckboxSelectInline, self).render(*args,**kwargs)
        return mark_safe(output.replace(u'<ul>', u'').replace(u'</ul>', u'').replace(u'<li>', u'').replace(u'</li>', u'').replace(u'<label ', u'<label class="checkbox inline" '))


class RadioSelectStacked(forms.RadioSelect):
    def render(self, *args, **kwargs):
        output = super(RadioSelectStacked, self).render(*args,**kwargs)
        return mark_safe(output.replace(u'<ul>', u'').replace(u'</ul>', u'').replace(u'<li>', u'').replace(u'</li>', u''))


class CustomCheckboxSelectMultipleIncomeTypeOnly(forms.CheckboxSelectMultiple):
    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = []
        attrs['class'] = 'asset_income_type'
        final_attrs = self.build_attrs(attrs, name=name)
        output = []
        # Normalize to strings
        str_values = set([force_text(v) for v in value])
        counter = 1
        for i in self.choices.queryset:
            cb = forms.CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
            option_value = force_text(i.id)
            rendered_cb = cb.render(name, option_value)
            option_label = conditional_escape(force_text(i.name))
            if counter % 2 == 0:
                output.append('<div class="span7"><label class="checkbox inline">%s %s</label>' % (rendered_cb, option_label))
                #if i.id == 9:
                #    output.append('<input type="text" name="asset_income_other" id="id_asset_income_other" disabled="disabled" title="Specify other type." class="input-medium" placeholder="Specify other..." />')
                output.append('</div></div>')
            else:
                output.append('<div class="row-fluid"><div class="span5"><label class="checkbox inline">%s %s</label>' % (rendered_cb, option_label))
                #if i.id == 9:
                #    output.append('<input type="text" name="asset_income_other" id="id_asset_income_other" disabled="disabled" title="Specify other type." class="input-medium" placeholder="Specify other..." /></div>')
                output.append('</div>')

            counter += 1

        return mark_safe('\n'.join(output))


class CustomCheckboxSelectMultipleAccountType(forms.CheckboxSelectMultiple):
    def render(self, name, value, attrs=None, choices=()):
        if value is None: value = []
        attrs['class'] = 'asset_income_type'
        final_attrs = self.build_attrs(attrs, name=name)
        output = []
        # Normalize to strings
        str_values = set([force_text(v) for v in value])
        counter = 1
        for i in self.choices.queryset:
            cb = forms.CheckboxInput(final_attrs, check_test=lambda value: value in str_values)
            option_value = force_text(i.id)
            rendered_cb = cb.render(name, option_value)
            option_label = conditional_escape(force_text(i.account_type))
            if counter % 2 == 0:
                output.append('<div class="span7"><label class="checkbox inline">%s %s</label>' % (rendered_cb, option_label))
                output.append('</div></div>')
            else:
                output.append('<div class="row-fluid"><div class="span5"><label class="checkbox inline">%s %s</label>' % (rendered_cb, option_label))
                output.append('</div>')
                if counter == len(self.choices.queryset):
                    output.append('</div>')

            counter += 1

        return mark_safe('\n'.join(output))

shared/views.py
from django.shortcuts import render

shared/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />

        <!-- Bootstrap CSS -->
        <link href="{% static 'plugins/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Font Awesome CSS -->
        <link href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <!-- animate.css CSS -->
        <link href="{% static 'plugins/animate/animate.min.css' %}" rel="stylesheet">
{#        <link href="{% static 'plugins/flexslider/flexslider.css' %}" rel="stylesheet">#}
        <link rel="stylesheet" type="text/css" href="{% static 'css/breakingNews.css' %}"/>
        <!-- Theme style -->
        <link href="{% static 'css/theme-style.css' %}" rel="stylesheet">
        <!-- Your custom override -->
        <link href="{% static 'css/custom-style.css' %}" rel="stylesheet">
        <!-- @option: Colour skins, choose from:
            1. colour-blue.css
            2. colour-red.css
            3. colour-grey.css
            4. colour-purple
            5. colour-green.css

            Uncomment line below to enable
        -->
    <!-- Flexslider -->

        <link href="{% static 'css/colour-blue.css' %}" rel="stylesheet" id="colour-scheme">

        {% block extra_css %}{% endblock %}

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="{% static 'plugins/html5shiv/dist/html5shiv.js' %}"></script>
        <script src="{% static 'plugins/respond/respond.min.js' %}"></script>
        <![endif]-->
    </head>

    <!-- ======== @Region: body ======== -->
    <body class="has-navbar-fixed-top page-index-carousel">
        <!-- ======== @Region: #navigation ======== -->
        <div id="navigation" class="wrapper">
            <!--Branding & Navigation Region-->
            <div class="navbar navbar-fixed-top" id="top">
                <div class="navbar-inner">
                    <div class="inner">
                        <div class="container">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle btn btn-navbar" data-toggle="collapse"
                                        data-target=".navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span> <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="{% url 'internal:home' %}" title="Home">
                                    <img src="{% static 'img/logo_warfighter.png' %}" style="position: absolute"/>
                                </a>
                            </div>
                            {% if request.user.is_authenticated %}
                                <div class="collapse navbar-collapse">
                                    <br/>
                                    <ul class="nav navbar-right" role="navigation" id="main-menu" style="position:relative">
                                        {% if request.user.account_type == 1 %}
                                            <li class="dropdown">
                                                <a href="" class="dropdown-toggle" id="forms-drop" data-toggle="dropdown">Forms</a>

                                                <!-- Dropdown Menu -->
                                                <ul class="dropdown-menu" role="menu" aria-labelledby="forms-drop">
                                                    <li role="menuitem"><a href="{% url 'internal:employee_forms' %}" tabindex="-1">Employee Forms</a></li>
                                                    <li role="menuitem"><a href="{% url 'internal:form_category' %}" tabindex="-1">Manage Form Categories</a></li>
                                                    <li role="menuitem"><a href="{% url 'internal:forms_items' %}" tabindex="-1">Manage Forms</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="{% url 'internal:contact_items' %}">Contact Items</a></li>
                                            <li><a href="{% url 'internal:featured_images' %}">Featured Images</a></li>
                                            <li><a href="{% url 'internal:news_items' %}">News Items</a></li>
                                            <li class="dropdown">
                                                <a href="" class="dropdown-toggle" id="contract-drop" data-toggle="dropdown">SeaPort-e</a>

                                                <!-- Dropdown Menu -->
                                                <ul class="dropdown-menu" role="menu" aria-labelledby="contract-drop">
                                                    <li role="menuitem"><a href="{% url 'internal:task_orders' %}" tabindex="-1">Task Orders</a></li>
                                                    <li role="menuitem"><a href="{% url 'internal:functional_capabilities' %}" tabindex="-1">Functional Capabilities</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="{% url 'security:team_members' %}">Team Members</a></li>
                                        {% else %}
                                            <li><a href="{% url 'internal:employee_forms' %}">Employee Forms</a></li>
                                        {% endif %}
                                        <li><a href="{% url 'security:logout' %}">Logout</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                            <!--/.nav-collapse -->
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div>
            {% block content_highlight %}{% endblock %}
            <div id="content">
                <div class="container">
                    <!--Message Block-->
                    {% include 'includes/message_block.html' %}
                    <!--End Message Block-->
                    {% block content %}{% endblock %}
                    <div class="push"></div>
                </div>
            </div>

        </div>

        <!-- ======== @Region: #footer ======== -->
        <footer id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col contact-block">
                        <address>
                            <small>
                                <strong>Naval Systems, Inc.</strong><br/>
                                21491 Great Mills Road, Suite 100 &#9679; Lexington Park, MD 20653<br/>
                                Phone: (301) 737-1911 &#9679; Fax: (301) 737-1940<br/>
                            </small>
                        </address>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <small>© 2016 Naval Systems, Inc.</small>
                    </div>
                </div>
            </div>
        </footer>

        <!--Scripts -->
        <script src="{% static 'js/jquery.js' %}"></script>

        <!-- Bootstrap Javascript -->
        <script src="{% static 'plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>

        <!--Plugins / Non-Bootstrap Javascript -->
        <script src="{% static 'plugins/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'plugins/isotope/dist/isotope.pkgd.min.js' %}"></script>
{#        <script src="{% static 'plugins/flexslider/jquery.flexslider-min.js' %}"></script>#}
        <script src="{% static 'js/breakingNews.js' %}"></script>

        <!--Custom scripts mainly used to trigger libraries -->
        <script src="{% static 'js/script.js' %}"></script>

        {% block extra_scripts %}{% endblock %}

    </body>
</html>