employees/urls.py
from django.conf.urls import patterns, url
from django.conf import settings


urlpatterns = patterns(
    'employees.views',
    url(r'^$', 'home', name='home'),

    # Featured Images
    url(r'^featured/images/$', 'featured_images', name='featured_images'),
    url(r'^process/featured/image/{}/$'.format(settings.UUID_PATTERN_REGEX), 'featured_images',
        name='edit_featured_image'),
    url(r'^delete/featured/image/{}/$'.format(settings.UUID_PATTERN_REGEX), 'delete_featured_image',
        name='delete_featured_image'),

    # News Items
    url(r'^news/items/$', 'news_items', name='news_items'),
    url(r'^process/news/item/{}/$'.format(settings.UUID_PATTERN_REGEX), 'news_items', name='edit_news_items'),
    url(r'^delete/news/item/{}/$'.format(settings.UUID_PATTERN_REGEX), 'delete_news_item', name='delete_news_item'),

    # Functional Capabilities
    url(r'^functional/capabilities/$', 'functional_capabilities', name='functional_capabilities'),
    url(r'^process/functional/capability/{}/$'.format(settings.UUID_PATTERN_REGEX), 'functional_capabilities',
        name='edit_func_capability'),
    url(r'^delete/functional/capability/{}/$'.format(settings.UUID_PATTERN_REGEX), 'delete_func_capability',
        name='delete_func_capability'),

    # Task Orders
    url(r'^task/orders/$', 'task_orders', name='task_orders'),
    url(r'^process/task/order/{}/$'.format(settings.UUID_PATTERN_REGEX), 'task_orders', name='edit_task_order'),
    url(r'^delete/task/order/{}/$'.format(settings.UUID_PATTERN_REGEX), 'delete_task_order', name='delete_task_order'),

    # Contact Items
    url(r'^contact/itemss/$', 'contact_items', name='contact_items'),
    url(r'^view/contact/item/{}/$'.format(settings.UUID_PATTERN_REGEX), 'contact_items', name='view_contact_item'),
    url(r'^delete/contact/item/{}/$'.format(settings.UUID_PATTERN_REGEX), 'delete_contact_item',
        name='delete_contact_item'),

    # Forms
    url(r'^form/categories/$', 'form_category', name='form_category'),
    url(r'^process/form/category{}/$'.format(settings.UUID_PATTERN_REGEX), 'form_category', name='edit_form_category'),
    url(r'^delete/form/category/{}/$'.format(settings.UUID_PATTERN_REGEX), 'delete_form_category',
        name='delete_form_category'),

    url(r'^forms/$', 'employee_forms', name='employee_forms'),
    url(r'^form/items/$', 'forms_items', name='forms_items'),
    url(r'^process/forms/item/{}/$'.format(settings.UUID_PATTERN_REGEX), 'forms_items', name='edit_forms_items'),
    url(r'^delete/forms/item/{}/$'.format(settings.UUID_PATTERN_REGEX), 'delete_forms_item', name='delete_forms_item'),
)

nsi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^', include('employees.urls', namespace='employees')),
    url(r'^security/', include('security.urls', namespace='security')),
    url(r'^admin/', admin.site.urls),

    # Shared Application
    url(r'^shared/', include('shared.urls', namespace='shared')),

    # url(r'^404/$', TemplateView.as_view(template_name='404.html',)),
    # url(r'^500/$', TemplateView.as_view(template_name='500.html',)),
]

security/urls.py
from django.conf import settings
from django.conf.urls import patterns, url


urlpatterns = patterns('security.views',
    url(r'^login/$', 'login_form', name='login'),
    url(r'^logout/$', 'user_logout', name='logout'),
    url(r'^password/reset/$', 'reset_password', name='reset_password'),
    url(r'^password/create/{uuid_pattern}/{uuid_pattern}/$'.format(uuid_pattern=settings.UUID_PATTERN_REGEX), 'create_new_password',
        name='create_new_password'),
    url(r'^team/members/$', 'team_members', name='team_members'),
    url(r'^team/member/{}/$'.format(settings.UUID_PATTERN_REGEX), 'team_members', name='edit_team_member')

)

employees/forms.py
from django import forms
from django.forms import ModelForm


from shared.models import NewsItem, FunctionalCapability, ImageItem, TaskOrder, FormData, FormCategory
from shared.forms import RadioSelectInline, CheckboxSelectInline


class NewsItemForm(ModelForm):
    bool_choices = ((True, 'Yes'), (False, 'No'))
    year_choices = [('', 'Select year...'), ]

    for x in range(2012, 2100):
        year_choices.append((x, x))

    is_active = forms.ChoiceField(choices=bool_choices, widget=RadioSelectInline, initial=True)
    news_year = forms.ChoiceField(choices=year_choices)

    class Meta:
        model = NewsItem
        fields = ['featured', 'title', 'text', 'is_active', 'news_year']


class FunctionalCapabilityForm(ModelForm):
    bool_choices = ((True, 'Yes'), (False, 'No'))

    is_active = forms.ChoiceField(choices=bool_choices, widget=RadioSelectInline, initial=True)

    class Meta:
        model = FunctionalCapability
        fields = ['title', 'text', 'is_active']


class TaskOrderForm(ModelForm):
    def __init__(self, *args, **kwargs):

        super(TaskOrderForm, self).__init__(*args, **kwargs)

        bool_choices = ((True, 'Yes'), (False, 'No'))

        self.fields['is_active'] = forms.ChoiceField(choices=bool_choices, widget=RadioSelectInline, initial=True)
        self.fields['document'].required = False

    class Meta:
        model = TaskOrder
        fields = ['task_number', 'document', 'is_active']


class ImageItemForm(ModelForm):
    def __init__(self, *args, **kwargs):

        super(ImageItemForm, self).__init__(*args, **kwargs)

        bool_choices = ((True, 'Yes'), (False, 'No'))

        self.fields['is_active'] = forms.ChoiceField(choices=bool_choices, widget=RadioSelectInline, initial=True)
        self.fields['featured'] = forms.ChoiceField(choices=bool_choices, widget=RadioSelectInline, initial=True)

    class Meta:
        model = ImageItem
        fields = ['title', 'text', 'image', 'is_active', 'featured']


class FormDataForm(ModelForm):
    def __init__(self, *args, **kwargs):

        super(FormDataForm, self).__init__(*args, **kwargs)

        bool_choices = ((True, 'Yes'), (False, 'No'))
        data_type_choices = (('form', 'Form'), ('link', 'Link'))

        self.fields['is_active'] = forms.ChoiceField(choices=bool_choices, widget=RadioSelectInline, initial=True)
        self.fields['data_type'] = forms.ChoiceField(choices=data_type_choices, initial='form')

    def clean(self):
        cleaned_data = super(FormDataForm, self).clean()
        data_type = cleaned_data.get('data_type')

        if data_type == 'form' and not cleaned_data.get('document'):
            self._errors['document'] = self.error_class('Please choose the form you would like to upload.')
        elif data_type == 'link' and not cleaned_data.get('link'):
            self._errors['link'] = self.error_class('A valid link is required')

    class Meta:
        model = FormData
        fields = ['title', 'document', 'is_active', 'category', 'data_type', 'link']


class FomCategoryForm(ModelForm):
    def __init__(self, *args, **kwargs):

        super(FomCategoryForm, self).__init__(*args, **kwargs)

        bool_choices = ((True, 'Yes'), (False, 'No'))

        self.fields['is_active'] = forms.ChoiceField(choices=bool_choices, widget=RadioSelectInline, initial=True)

    class Meta:
        model = FormCategory
        fields = ['category', 'is_active']

employees/views.py
import os
import shutil
import urllib3

from django.shortcuts import render, redirect
from django.contrib import messages
from django.conf import settings

from employees.forms import NewsItemForm, FunctionalCapabilityForm, TaskOrderForm, ImageItemForm, FormDataForm, \
    FomCategoryForm
from shared.models import NewsItem, FunctionalCapability, TaskOrder, ImageItem, ContactItem, FormData, FormCategory
from shared.utilities import collect_static

http = urllib3.PoolManager()


def home(request):
    return render(request, 'home.html')


def news_items(request, news_uuid=None):
    items = NewsItem.objects.all()
    news_item = None

    if news_uuid:
        try:
            news_item = items.get(news_uuid=news_uuid)
        except NewsItem.DoesNotExist:
            messages.error(request, 'The news item selected to be edited no longer exists.')

            return redirect('employees:news_items')

    if request.method == 'POST':
        form = NewsItemForm(request.POST, instance=news_item)

        if form.is_valid():
            item = form.save(commit=False)
            item.updated_by = request.user
            item.save()

            messages.success(request, 'The news item was saved successfully.')
            return redirect('employees:news_items')
        else:
            messages.error(request, settings.GENERIC_ERROR)
    else:
        form = NewsItemForm(instance=news_item)

    return render(request, 'news_items.html', {'form': form, 'news_items': items, 'news_uuid': news_uuid})


def delete_news_item(request, news_uuid):
    try:
        news_item = NewsItem.objects.get(news_uuid=news_uuid)
        news_item.delete()

        messages.success(request, 'The news items was deleted')
    except NewsItem.DoesNotExist:
        messages.error(request, 'The news item selected to be deleted no longer exists.')
    except Exception as e:
        messages.error(request, 'An error occurred deleting the selected new item.  Please try again.')

    return redirect('employees:news_items')


def functional_capabilities(request, capability_uuid=None):
    items = FunctionalCapability.objects.all()
    func_capability_item = None

    if capability_uuid:
        try:
            func_capability_item = items.get(capability_uuid=capability_uuid)
        except FunctionalCapability.DoesNotExist:
            messages.error(request, 'The functional capability selected to be edited no longer exists.')

            return redirect('employees:functional_capabilities')

    if request.method == 'POST':
        form = FunctionalCapabilityForm(request.POST, instance=func_capability_item)

        if form.is_valid():
            item = form.save(commit=False)
            item.updated_by = request.user
            item.save()

            messages.success(request, 'The functional capability was saved successfully.')
            return redirect('employees:functional_capabilities')
        else:
            messages.error(request, settings.GENERIC_ERROR)
    else:
        form = FunctionalCapabilityForm(instance=func_capability_item)

    return render(request, 'functional_capabilities.html', {'form': form, 'func_items': items,
                                                            'capability_uuid': capability_uuid})


def delete_func_capability(request, capability_uuid):
    try:
        func_capability_item = FunctionalCapability.objects.get(capability_uuid=capability_uuid)
        func_capability_item.delete()

        messages.success(request, 'The functional capability was deleted')
    except FunctionalCapability.DoesNotExist:
        messages.error(request, 'The functional capability selected to be deleted no longer exists.')
    except Exception as e:
        messages.error(request, 'An error occurred deleting the selected functional capability.  Please try again.')

    return redirect('employees:functional_capabilities')


def task_orders(request, task_uuid=None):
    items = TaskOrder.objects.all()
    task_order_item = None

    if task_uuid:
        try:
            task_order_item = items.get(task_uuid=task_uuid)
        except TaskOrder.DoesNotExist:
            messages.error(request, 'The task order selected to be edited no longer exists.')

            return redirect('employees:task_orders')

    if request.method == 'POST':
        form = TaskOrderForm(request.POST, request.FILES, instance=task_order_item)

        if form.is_valid():
            item = form.save(commit=False)
            item.updated_by = request.user
            item.save()

            collect_static()
            # document
            # taskorder_update

            if settings.IS_PROD:
                # copy the document to the public site
                shutil.copy(item.document.url, '{}/{}'.format(settings.DOCUMENT_PATH, item.get_document_name))
                http.request('GET', settings.PUBLIC_URL)

            messages.success(request, 'The task order was saved successfully.')
            return redirect('employees:task_orders')
        else:
            messages.error(request, settings.GENERIC_ERROR)
    else:
        form = TaskOrderForm(instance=task_order_item)

    return render(request, 'task_orders.html', {'form': form, 'task_order_items': items, 'task_uuid': task_uuid})


def delete_task_order(request, task_uuid):
    try:
        task_order_item = TaskOrder.objects.get(task_uuid=task_uuid)
        task_order_item.delete()

        messages.success(request, 'The task order was deleted')
    except TaskOrder.DoesNotExist:
        messages.error(request, 'The task order selected to be deleted no longer exists.')
    except Exception as e:
        messages.error(request, 'An error occurred deleting the selected task order.  Please try again.')

    return redirect('employees:task_orders')


def featured_images(request, image_uuid=None):
    items = ImageItem.objects.all()
    image_item = None

    if image_uuid:
        try:
            image_item = items.get(image_uuid=image_uuid)
        except ImageItem.DoesNotExist:
            messages.error(request, 'The featured image selected to be edited no longer exists.')

            return redirect('employees:featured_images')

    if request.method == 'POST':
        form = ImageItemForm(request.POST, request.FILES, instance=image_item)

        if form.is_valid():
            item = form.save(commit=False)
            item.updated_by = request.user
            item.save()

            collect_static()
            # image
            # imageitem_udpate

            messages.success(request, 'The featured image was saved successfully.')
            return redirect('employees:featured_images')
        else:
            messages.error(request, settings.GENERIC_ERROR)
    else:
        form = ImageItemForm(instance=image_item)

    return render(request, 'featured_images.html', {'form': form, 'featured_image_items': items,
                                                    'image_uuid': image_uuid})


def delete_featured_image(request, image_uuid):
    try:
        image_item = ImageItem.objects.get(image_uuid=image_uuid)
        image_item.delete()

        messages.success(request, 'The featured image was deleted')
    except ImageItem.DoesNotExist:
        messages.error(request, 'The featured image selected to be deleted no longer exists.')
    except Exception as e:
        messages.error(request, 'An error occurred deleting the selected featured image.  Please try again.')

    return redirect('employees:featured_images')


def contact_items(request, contact_uuid=None):
    items = ContactItem.objects.all()
    contact_item = None

    if contact_uuid:
        try:
            contact_item = items.get(contact_uuid=contact_uuid)
        except ImageItem.DoesNotExist:
            messages.error(request, 'The contact item selected to be edited no longer exists.')

            return redirect('employees:contact_items')

    return render(request, 'contact_items.html', {'contact_items': items, 'contact_uuid': contact_uuid,
                                                  'contact_item': contact_item})


def delete_contact_item(request, contact_uuid):
    try:
        contact_item = ContactItem.objects.get(contact_uuid=contact_uuid)
        contact_item.delete()

        messages.success(request, 'The contact item was deleted')
    except ContactItem.DoesNotExist:
        messages.error(request, 'The contact item selected to be deleted no longer exists.')
    except Exception as e:
        messages.error(request, 'An error occurred deleting the selected contact item image.  Please try again.')

    return redirect('employees:contact_items')


def forms_items(request, form_uuid=None):
    items = FormData.objects.filter(is_active=True)
    form_item = None

    if form_uuid:
        try:
            form_item = items.get(form_uuid=form_uuid)
        except FormData.DoesNotExist:
            messages.error(request, 'The form selected to be edited no longer exists.')

            return redirect('employees:forms_items')

    if request.method == 'POST':
        form = FormDataForm(request.POST, request.FILES, instance=form_item)

        if form.is_valid():
            item = form.save(commit=False)
            item.updated_by = request.user
            item.save()
            form.save_m2m()

            collect_static()
            # document
            # formitem_update
            with sys.wr
            messages.success(request, 'The form was saved successfully.')
            return redirect('employees:forms_items')
        else:
            messages.error(request, settings.GENERIC_ERROR)
    else:
        form = FormDataForm(instance=form_item)

    return render(request, 'manage_forms.html', {'form': form, 'form_items': items, 'form_uuid': form_uuid})


def delete_forms_item(request, form_uuid):
    try:
        form_item = FormData.objects.get(form_uuid=form_uuid)

        # remove the uploaded file.
        form_item.document.delete()

        form_item.delete()

employees/templates/contact_items.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load html_attributes %}

{% block extra_styles %}
    <link type="text/css" href="{% static 'datatables.css' %}" rel="stylesheet"
		  media="all" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block extra_scripts %}
    <script src="{% static 'ckeditor/ckeditor.js' %}" type="text/javascript"></script>
    <script src="{% static 'datatables.min.js' %}" type="text/javascript"></script>
    <script>
        $(document).ready(function(){
            $('#grid_items').dataTable( {
                "dom": '<"top"<"pull-left input-short"f><"pull-right"i><"clear">>rt<"bottom"p<"clear">>',  //placement of the search box to the left
                "paging": true,       //turn off paging so that all results show
                "pageLength": 25,
                "lengthChange": false, //drop-down for pagination
                "searching": true,     //search box
                "info": true,          //showing # of # line
                "orderClasses": false, // removes sorted column styles from being applied
                "order":[[0,'asc']],   //identify the column to sort by default
                "processing": true,    //when waiting for the data to load, show overlay
                "serverSide": false,   //where the table is generated
                "columnDefs":[
                    {"orderable": false, "targets": []}, // columns to exempt when ordering
                    {"searchable": false, "targets": []} // columns to exempt when searching
                ],
                "language": {
                  "emptyTable": "There are no contact items.", // message that appears if the table is empty when the pg loads
                  "zeroRecords": "No matching contact items.", // message that appears after you search if there are no matches
                  "search": ""  // changes label of search box
                }
            } );
            $('.dataTables_filter input').attr("placeholder", "To filter list, start typing.");

            CKEDITOR.replace( '{{ form.text.auto_id }}' );
        });
    </script>
{% endblock %}


{% block title %}Contact Items{% endblock %}
{% block content_highlight %}
    <!-- ======== @Region: #highlighted ======== -->
    <div id="highlighted">
        <div class="container">
            <div class="header">
                <h2 class="page-title">
                    <span>Contact Items</span>
                </h2>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="block">
        <div class="row">
            <div class="col-md-12">
                <table id="grid_items" class="table table-striped table-hover dataTable">
                    <caption style="display: none"></caption>
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Category</th>
                            <th scope="col">Message</th>
                            <th scope="col">Date</th>
                            <th scope="col">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for contact_item in contact_items %}
                        <tr>
                            <td>{{ contact_item.name }}</td>
                            <td>{{ contact_item.email }}</td>
                            <td>{{ contact_item.category }}</td>
                            <td>{{ contact_item.message }}</td>
                            <td>{{ contact_item.dt_updated|date:"n/d/Y" }}</td>
                            <td><a href="{% url 'employees:delete_contact_item' contact_item.contact_uuid %}" title="Delete contact item."><i class="fa fa-trash"></i> </a> </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

employees/templates/form_categories.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load html_attributes %}

{% block extra_styles %}
    <link type="text/css" href="{% static 'datatables.css' %}" rel="stylesheet"
		  media="all" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
{% endblock %}
{% block extra_scripts %}
    <script src="{% static 'ckeditor/ckeditor.js' %}" type="text/javascript"></script>
    <script src="{% static 'datatables.min.js' %}" type="text/javascript"></script>
    <script>
        $(document).ready(function(){
            $('#grid_items').dataTable( {
                "dom": '<"top"<"pull-left input-short"f><"pull-right"i><"clear">>rt<"bottom"p<"clear">>',  //placement of the search box to the left
                "paging": true,       //turn off paging so that all results show
                "pageLength": 25,
                "lengthChange": false, //drop-down for pagination
                "searching": true,     //search box
                "info": true,          //showing # of # line
                "orderClasses": false, // removes sorted column styles from being applied
                "order":[[0,'asc']],   //identify the column to sort by default
                "processing": true,    //when waiting for the data to load, show overlay
                "serverSide": false,   //where the table is generated
                "columnDefs":[
                    {"orderable": false, "targets": []}, // columns to exempt when ordering
                    {"searchable": false, "targets": []} // columns to exempt when searching
                ],
                "language": {
                  "emptyTable": "There are no categories.", // message that appears if the table is empty when the pg loads
                  "zeroRecords": "No matching categories.", // message that appears after you search if there are no matches
                  "search": ""  // changes label of search box
                }
            } );
            $('.dataTables_filter input').attr("placeholder", "To filter list, start typing.");

            CKEDITOR.replace( '{{ form.text.auto_id }}' );
        });
    </script>
{% endblock %}


{% block title %}Manage Form Categories{% endblock %}
{% block content_highlight %}
    <!-- ======== @Region: #highlighted ======== -->
    <div id="highlighted">
        <div class="container">
            <div class="header">
                <h2 class="page-title">
                    <span>Manage Form Categories</span>
                </h2>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="block">
        <div class="row">
            <div class="col-md-6">
                <p>Categories with associated forms cannot be deleted until all forms are removed or their category switched.</p>
                <table id="grid_items" class="table table-striped table-hover dataTable">
                    <caption style="display: none"></caption>
                    <thead>
                        <tr>
                            <th scope="col">Category</th>
                            <th scope="col">Associated Forms</th>
                            <th scope="col">Active</th>
                            <th scope="col">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td>
                                {{ item.category }}
                                <small class="media-body">
                                    <ul class="list-inline meta text-muted">
                                      <li>
                                          <i class="glyphicon glyphicon-calendar"></i>
                                          <span class="visible-md-inline visible-lg-inline">Date:</span>
                                          {{ item.dt_updated|date:"n/d/Y @ f A" }}
                                      </li>
                                      <li>
                                          <i class="glyphicon glyphicon-user"></i>
                                          <span class="visible-md-inline visible-lg-inline">By</span>
                                          <a href="{% url 'security:edit_team_member' item.updated_by.user_uuid %}">
                                              {{ item.updated_by.get_full_name }}</a>
                                      </li>
                                    </ul>
                                </small>
                            </td>
                            <td>
                                {% for form in item.has_links_or_documents.documents %}
                                    {{ form.title }}{% if not forloop.last %}, {% endif %}<br/>
                                {% endfor %}
                            </td>
                            <td align="center"><i class="glyphicon glyphicon- {% if item.is_active %}glyphicon-{% else %}glyphicon-eye-close{% endif %} text-info" /></i></td>
                            <td class="edit_column">
                                <a href="{% url 'employees:edit_form_category' item.category_uuid %}" title="Edit Category."><i class="fa fa-pencil"></i> </a>
                                {% if not item.has_links_or_documents.documents and not item.has_links_or_documents.links %}
                                    <span class="padit">|</span>
                                    <a href="{% url 'employees:delete_form_category' item.category_uuid %}" title="Delete form."><i class="fa fa-trash alert-danger"></i> </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-6 sidebar sidebar-right">
                <div class="inner">
                    <div class="block">
                        <h3 class="block-title sub-title">
                            <span>{% if category_uuid %}Edit the{% else %}Add a{% endif %} Form Category</span>
                        </h3>
                        <form action="" method="POST" enctype="multipart/form-data">
                            <div class="form-group{% if form.category.errors  %} has-error{% endif %}">
                                {% if form.category.errors %}
                                    <label class="control-label" for="{{ form.category.auto_id }}">
                                        <i class="fa fa-exclamation-triangle"></i> Category is required.
                                    </label><br>
                                {% endif %}
                                {{ form.category|htmlattributes:"class: form-control, placeholder:Category" }}
                            </div>
                           <div class="form-group{% if form.is_active.errors  %} has-error{% endif %}">
                                <fieldset>
                                    <div class="controls">
                                        <label>Active</label>
                                        {{ form.is_active }}
                                    </div>
                                </fieldset>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a href="{% url 'employees:form_category' %}">Cancel</a>
                            </div>
                            <input type="hidden" name="category_uuid" value="{{ category_uuid }}"/>
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

employees/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Home{% endblock %}
{% block content %}
    <div id="highlighted">
        <div class="inner">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="header">
                            <h2 class="page-title">
                                <span>Quality, Integrity and Victory</span>
                            </h2>
                        </div>
                        <p class="home">
                            Welcome to the NSI Employee Portal
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}