nsi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^', include('employees.urls', namespace='employees')),
    url(r'^security/', include('security.urls', namespace='security')),
    url(r'^admin/', admin.site.urls),

    # Shared Application
    url(r'^shared/', include('shared.urls', namespace='shared')),

    # url(r'^404/$', TemplateView.as_view(template_name='404.html',)),
    # url(r'^500/$', TemplateView.as_view(template_name='500.html',)),
]

security/urls.py
from django.conf import settings
from django.conf.urls import patterns, url


urlpatterns = patterns('security.views',
    url(r'^login/$', 'login_form', name='login'),
    url(r'^logout/$', 'user_logout', name='logout'),
    url(r'^password/reset/$', 'reset_password', name='reset_password'),
    url(r'^password/create/{uuid_pattern}/{uuid_pattern}/$'.format(uuid_pattern=settings.UUID_PATTERN_REGEX), 'create_new_password',
        name='create_new_password'),
    url(r'^team/members/$', 'team_members', name='team_members'),
    url(r'^team/member/{}/$'.format(settings.UUID_PATTERN_REGEX), 'team_members', name='edit_team_member')

)

security/models.py
from uuid import uuid4

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

from shared.utilities import make_uuid


class CustomUserManager(BaseUserManager):
    def create_user(self, email, account_type, password=str(uuid4)):
        if not email:
            raise ValueError('Email address is required to create a user')

        if not account_type:
            raise ValueError('Account Type is required to create a user')

        user = self.model(email=self.normalize_email(email), account_type=account_type)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Creates and saves a super User with the given email and password.
        """

        email = self.normalize_email(email)
        user = self.model(email=email, is_admin=True, is_active=True, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=250, blank=True, null=True, verbose_name='User Name')
    user_uuid = models.CharField(max_length=36, default=make_uuid, db_index=True)
    account_type = models.IntegerField()
    first_name = models.CharField(max_length=100, verbose_name='First Name')
    last_name = models.CharField(max_length=100, verbose_name='Last Name')
    office_phone = models.CharField(max_length=14, null=True, blank=True, verbose_name='office phone')
    mobile_phone = models.CharField(max_length=14, null=True, blank=True, verbose_name='mobile phone')
    email = models.EmailField(max_length=250, unique=True, db_index=True)
    password_reset = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False, verbose_name='Is Active')
    is_admin = models.BooleanField(default=False, verbose_name='Is Superuser', help_text='Django admin user.')
    dt_created = models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Date/Time Created')
    dt_updated = models.DateTimeField(auto_now=True, blank=True, verbose_name='Date/Time Updated')
    dt_last_login = models.DateTimeField(blank=True, null=True, verbose_name='Date/Time Last Login')
    dt_password_reset = models.DateTimeField(verbose_name='Date/Time Password Reset', blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['account_type']

    @property
    def get_account_type_string(self):
        at = self.account_type

        return 'Administrator' if at == 1 else 'General User'

    @property
    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def get_short_name(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin

    def email_link(self):
        return '<a href="mailto:{}">{}</a>'.format(self.email, self.email)

    email_link.allow_tags = True

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_superuser(self):
        """
        This mirror `is_admin` attribute
        :return: Boolean
        """
        return self.is_admin

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        unique_together = ['email', 'account_type']
        ordering = ['email', ]

security/forms.py
from django import forms
from django.forms import ModelForm

from shared.forms import RadioSelectInline
from security.models import CustomUser


class LoginForm(forms.Form):
    email = forms.CharField(error_messages={'required': 'Please enter your email address.'})
    password = forms.CharField(error_messages={'required': 'Please enter your password.'},
                               widget=forms.PasswordInput(attrs={'maxlength': 100}))


class CreatePasswordForm(forms.Form):
    password = forms.CharField(error_messages={'required': 'Please enter your email address.'},
                               widget=forms.PasswordInput(attrs={'maxlength': 100}))
    password_verify = forms.CharField(widget=forms.PasswordInput(attrs={'maxlength': 100}))


class ResetPasswordForm(forms.Form):
    email = forms.CharField(error_messages={'required': 'Please enter your email address.'})


class CustomUserForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)

        account_types = [(1, 'Administrator'), (2, 'General User')]
        bool_choices = ((True, 'Yes'), (False, 'No'))

        self.fields['mobile_phone'].required = False
        self.fields['email'].error_messages = {'required': 'Email is required.'}
        self.fields['account_type'] = forms.ChoiceField(choices=account_types, widget=RadioSelectInline)
        self.fields['is_active'] = forms.ChoiceField(choices=bool_choices, widget=RadioSelectInline, initial=True)

    class Meta(object):
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'office_phone', 'mobile_phone', 'account_type', 'is_active']

security/views.py
import re
import uuid
from datetime import datetime, timedelta

from django.conf import settings
from django.shortcuts import redirect, render
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.db import transaction
from django.core.urlresolvers import reverse

from security.forms import LoginForm, CreatePasswordForm, ResetPasswordForm, CustomUserForm
from shared.utilities import random_password_generator, make_uuid

from .backends import AuthenticationFailedException

User = get_user_model()


def login_form(request, template_name='login.html'):
    try:
        with transaction.atomic():
            has_error = False
            authentication_error = None

            if request.user.is_authenticated():
                return redirect('employees:home')

            if request.method == 'POST':
                if request.user.is_authenticated():
                    return redirect(request.POST.get('next', 'employees:home'))

                form = LoginForm(request.POST)

                email = request.POST['email'].lower()
                password = request.POST['password']

                if form.is_valid():
                    user = authenticate(email=email, password=password)

                    if user:
                        if user.is_active:
                            # check to see if the user has reset their password and if the time period has expired
                            if user.password_reset:
                                account_tdelta = user.dt_password_reset + timedelta(
                                    hours=settings.TEMP_PASSWORD_EXPIRES)

                                if datetime.now().strftime("%Y-%m-%d %H:%M:%S") >= account_tdelta.strftime("%Y-%m-%d %H:%M:%S"):
                                    messages.error(request, 'Your temporary password has expired.  You must request a new one.')
                                    return redirect('reset_password')

                            if user.password_reset:
                                return redirect('create_new_password', user.user_uuid)

                            user.backend = settings.AUTHENTICATION_BACKENDS[0]

                            login(request, user)

                            # record the date/time the user last logged in.
                            user.dt_last_login = datetime.now()
                            user.save()

                            return redirect(request.POST.get('next', 'employees:home'))
                        else:
                            has_error = True
                            messages.error(request, 'You do not have an active account.')
                    else:
                        authentication_error = True
                        has_error = True
                        messages.error(request, settings.GENERIC_ERROR)
                else:
                    has_error = True
                    messages.error(request, settings.GENERIC_ERROR)
            else:
                form = LoginForm()
    except AuthenticationFailedException as e:
        messages.error(request, e)
        authentication_error = True
    except Exception as e:
        messages.error(request, 'An error occurred: {} - {}'.format(type(e), e))

    return render(request, template_name, locals())


def user_logout(request):
    logout(request)

    messages.success(request, 'You have logged out.')
    return redirect('security:login')


def create_new_password(request, user_uuid, temporary_password, template_name='createNewPassword.html'):
    password_error = False

    try:
        user = User.objects.get(user_uuid=user_uuid)
    except User.DoesNotExist:
        messages.error(request, 'A password reset could not be processed.')
        return redirect('security:reset_password')

    if request.method == 'POST':
        form = CreatePasswordForm(request.POST)

        password = request.POST.get('password')
        password_verify = request.POST.get('password_verify')

        if not re.match(settings.PASSWORD_REGEX, password):
            messages.error(request, 'Your password does not meet the complexity requirements.')
            password_error = True

            return redirect('security:create_new_password', user_uuid, temporary_password)

        if password != password_verify:
            messages.error(request, 'Your passwords do not match')
            password_error = True

            return redirect('security:create_new_password', user_uuid, temporary_password)

        if form.is_valid():
            user.set_password(password)
            user.password_reset = False
            user.dt_password_reset = None
            user.dt_last_login = datetime.now()
            user.save()

            user.backend = settings.AUTHENTICATION_BACKENDS[0]

            login(request, user)
            messages.success(request, 'Your password has been successfully reset.')

            return redirect('employees:home')
    else:
        if user.check_password(temporary_password):
            # check to see if the time period for use this password has expired.
            account_time_delta = user.dt_password_reset + timedelta(hours=settings.TEMP_PASSWORD_EXPIRES)

            if datetime.now().strftime("%y-%m-%d %H:%M:%S") >= account_time_delta.strftime("%y-%m-%d %H:%M:%S"):
                messages.error(request, 'Your temporary password has expired.  You must request a new one')

                return redirect('security:reset_password')

            form = CreatePasswordForm()
        else:
            messages.error(request, 'The temporary password provided is not valid.  Please try again.')
            return redirect('security:reset_password')

    return render(request, template_name, locals())


def reset_password(request, template_name='resetPassword.html'):
    temp_expire = settings.TEMP_PASSWORD_EXPIRES

    if request.method == 'POST':
        try:
            form = ResetPasswordForm(request.POST)

            if form.is_valid():
                # Random string 10 characters long based on upper, lower, digits and special characters
                new_password = make_uuid()

                email = request.POST['email'].lower()

                user = User.objects.get(email=email)
                user.set_password(new_password)
                user.password_reset = True
                user.dt_password_reset = datetime.now()
                user.save()

                url_pattern = '{}{}'.format(settings.APPLICATION_URL, reverse('security:create_new_password',
                                                                              args=(user.user_uuid, new_password)))

                email_subject = 'NSI Employee Portal Password Reset'
                email_body = """
<p>{first_name}</p>
<p>You have requested a password reset through the NSI Employee Portal. The following link will reset your password.
<a href="{url_pattern}">Please click here to continue.</a></p>
<p>Please keep in mind this temporary password will expire in {password_expire} hours. Upon clicking the link you will
be prompted to create a new password.</p>""".format(first_name=user.first_name, url_pattern=url_pattern,
                                                    password_expire=settings.TEMP_PASSWORD_EXPIRES)

                email = EmailMultiAlternatives(email_subject, '', settings.APPLICATION_EMAIL, [email])
                email.attach_alternative(email_body, "text/html")

                email.send(fail_silently=False)

                messages.success(request, """Your password reset has been processed. You will receive an email
                                          containing a temporary password.""")

                return redirect('security:login')
            else:
                # form is not valid
                messages.error(request, settings.GENERIC_ERROR)
        except User.DoesNotExist:
            messages.error(request, 'A password reset request could not be processed for this email address.')
            return redirect('security:reset_password')
    else:
        form = ResetPasswordForm()

    return render(request, template_name, {'form': form, 'temp_expire': temp_expire})


def team_members(request, user_uuid=None):
    team_member_data = User.objects.all()
    user = None

    if user_uuid:
        user = team_member_data.get(user_uuid=user_uuid)

    if request.method == 'POST':
        if user:
            form = CustomUserForm(request.POST, instance=user)
        else:
            form = CustomUserForm(request.POST)

        if form.is_valid():
            team_member = form.save(commit=False)
            team_member.email = team_member.email.lower()
            team_member.save()

            if not user:
                new_password = make_uuid()
                team_member.set_password(new_password)
                url_pattern = '{}{}'.format(settings.APPLICATION_URL, reverse('security:create_new_password',
                                                                              args=(team_member.user_uuid, new_password)))

                # the employee is new so send them an email with their password.
                email_subject = 'NSI Employee Portal Account Created'

                email_body = """
<p>{first_name}</p>,
<p>An account in the NSI Employee Portal has been created for you.  Please <a href="{url_pattern}">click here</a>
to login.</p>
<p>Please keep in mind this temporary password will expire in {expires} hours. Upon clicking the link you will be
prompted to create a new password.</p>""".format(first_name=team_member.first_name, url_pattern=url_pattern,
                                                 expires=settings.TEMP_PASSWORD_EXPIRES)

                email = EmailMultiAlternatives(email_subject, '', settings.APPLICATION_EMAIL, [team_member.email])

security/templates/manage_profile.html
{% extends 'base.html' %}

{% load html_attributes %}

{% block extra_styles %}{% endblock %}

{% block title %}
    {% if request.current_url_name == 'create_admin_profile' %}Create Account{% else %}Update Profile{% endif %}
{% endblock %}

{% block extra_scripts %}
    <script>
        $(document).ready(function(){
            //Hide Password Match indicator
            $('#match_pswd').hide()

            $('#{{ custom_user_form.password.auto_id }}').keyup(function() {
                // set password variable
                var pswd = $(this).val();
                var confirm_pswd = $('#id_password_verify').val();

                $('#match_pswd').show()

                //validate the length
                if ( pswd.length < 10 ) {
                    $('#length').removeClass('valid').addClass('invalid');
                    $('#length i').removeClass('icon-ok').addClass('icon-remove').attr('title','Bang does not meet criteria');
                } else {
                    $('#length').removeClass('invalid').addClass('valid');
                    $('#length i').removeClass('icon-remove').addClass('icon-ok').attr('title','Meets criteria');
                }

                //validate lower letter
                if (pswd.match(/[a-z]/)) {
                    $('#lower').removeClass('invalid').addClass('valid');
                    $('#lower i').removeClass('icon-remove').addClass('icon-ok').attr('title','Meets criteria');
                } else {
                    $('#lower').removeClass('valid').addClass('invalid');
                    $('#lower i').removeClass('icon-ok').addClass('icon-remove').attr('title','Bang does not meet criteria');
                }

                //validate capital letter
                if (pswd.match(/[A-Z]/)) {
                    $('#capital').removeClass('invalid').addClass('valid');
                    $('#capital i').removeClass('icon-remove').addClass('icon-ok').attr('title','Meets criteria');
                } else {
                    $('#capital').removeClass('valid').addClass('invalid');
                    $('#capital i').removeClass('icon-ok').addClass('icon-remove').attr('title','Bang does not meet criteria');
                }

                //validate number
                if (pswd.match(/\d+/)) {
                    $('#number').removeClass('invalid').addClass('valid');
                    $('#number i').removeClass('icon-remove').addClass('icon-ok').attr('title','Meets criteria');
                } else {
                    $('#number').removeClass('valid').addClass('invalid');
                    $('#number i').removeClass('icon-ok').addClass('icon-remove').attr('title','Bang does not meet criteria');
                }

                //validate symbol
                if (pswd.match(/[\!@#$%^&\*\(\)]/)) {
                    $('#symbol').removeClass('invalid').addClass('valid');
                    $('#symbol i').removeClass('icon-remove').addClass('icon-ok').attr('title','Meets criteria');
                } else {
                    $('#symbol').removeClass('valid').addClass('invalid');
                    $('#symbol i').removeClass('icon-ok').addClass('icon-remove').attr('title','Bang does not meet criteria');
                }

                //Passwords Match
                if (pswd == confirm_pswd){
                    $('#match_pswd').removeClass('invalid').addClass('valid');
                    $('#match_pswd i').removeClass('icon-remove').addClass('icon-ok').attr('title','Meets criteria');
                } else {
                    $('#match_pswd').removeClass('valid').addClass('invalid');
                    $('#match_pswd i').removeClass('icon-ok').addClass('icon-remove').attr('title','Bang does not meet criteria');
                }
            });

            $('#id_password_verify').keyup(function() {
                // set password variable
                var confirm_pswd = $(this).val();
                var pswd = $('#id_password').val();

                $('#match_pswd').show()

                //Passwords Match
                if (pswd == confirm_pswd){
                    $('#match_pswd').removeClass('invalid').addClass('valid');
                    $('#match_pswd i').removeClass('icon-remove').addClass('icon-ok').attr('title','Meets criteria');
                } else {
                    $('#match_pswd').removeClass('valid').addClass('invalid');
                    $('#match_pswd i').removeClass('icon-ok').addClass('icon-remove').attr('title','Bang does not meet criteria');
                }
            });
        });
    </script>
{% endblock %}

{% block content_one %}
    <div class="page-header">
        <h1>
            {% if request.current_url_name == 'create_admin_profile' %}Create Admin Account{% else %}Update Admin Account{% endif %}
        </h1>
    </div>

    <section class="account printForm">
        <div class="well well-small">
            <form action="" method="POST" class="form-horizontal form-highlightRow">
                <fieldset class="label-inline">
                    <legend>Staff Name</legend>
                    <div class="control-group{% if form.first_name.errors or form.last_name.errors %} error{% endif %}" >
                        <label class="control-label" for="{{ form.first_name.auto_id }}">First,&nbsp;</label>
                        <label class="control-label" for="{{ form.last_name.auto_id }}">Last</label>
                        <div class="controls">
                            {% if form.first_name.errors or form.last_name.errors %}<span class="help-inline"><i class="icon-warning-sign" title="Bang"></i> First and last name are required.</span><br>{% endif %}
                            {{ form.first_name|htmlattributes:"class:input-large, placeholder:First Name" }}
                            {{ form.last_name|htmlattributes:"class:input-xlarge, placeholder:Last Name" }}
                        </div>
                    </div>
                </fieldset>

                <fieldset>
                    <legend>Account Details</legend>

                    {% if request.user.administrative_user.office == 'GAO' and request.user.administrative_user.account_type.id == 2 %}
                        <input type="hidden" name="account_type" id="id_account_type" value="2" />
                    {% else %}
                        <div class="control-group">
                            <fieldset>
                                <legend class="control-label">Access Level</legend>
                                <div class="controls">
                                    {{ form.account_type }}
                                    {% if request.user.administrative_user.office|lower == 'gao' %}
                                        <br>
                                        <em class="muted">
                                            <i class="icon-warning-sign" title="Bang"></i> <strong>Note</strong> Level 2 administrators are considered Conflict Reviewers and will not have any other administrative functions.
                                    </em>
                                    {% endif %}
                                </div>
                            </fieldset>
                        </div>
                    {% endif %}

                    <div class="control-group{% if custom_user_form.email.errors or email_exists%} error{% endif %}">
                        <label class="control-label" for="{{ custom_user_form.email.auto_id }}">Email</label>
                        <div class="controls">
                            {% if custom_user_form.email.errors %}<span class="help-inline"><i class="icon-warning-sign" title="Bang"></i> {{ custom_user_form.email.errors|striptags }}</span><br>{% endif %}
                            {{ custom_user_form.email|htmlattributes:"class:input-xxlarge, placeholder:Your email" }}

                        </div>
                    </div>
                    <div class="control-group{% if custom_user_form.email.errors or email_error or email_exists%} error{% endif %}">
                        <label class="control-label" for="id_email_verify">Confirm email</label>
                        <div class="controls">
                            {% if email_error %}<span class="help-inline"><i class="icon-warning-sign" title="Bang"></i> Email does not match. Try again.</span><br>{% endif %}
                            <input type="text" name="email_verify" id="id_email_verify" class="input-xxlarge" placeholder="Re-enter your email." value="{{ email_verify }}"/>

                        </div>
                    </div>

                    {% if request.user.administrative_user.administrative_uuid == form.administrative_uuid.value  %}
                        <div class="row-fluid">
                            <div class="muted">
                                <i>To keep current password, leave blank. To change, enter a new password.</i>
                            </div>
                            <div class="span6 pull-right" id="pswd_info">
                                Passwords can not contain spaces but must include <strong>at least</strong>:

                                <ul>
                                    <li id="length" class=""><i class=""></i>10 characters</li>
                                    <li id="capital" class=""><i class=""></i>1 capital letter</li>
                                    <li id="lower" class=""><i class=""></i>1 lowercase letter</li>
                                    <li id="number" class=""><i class=""></i>1 number</li>
                                    <li id="symbol" class=""><i class=""></i>1 symbol ! @ # $ % ^ & * ( )</li>
                                </ul>
                            </div>
                            <div class="span6">
                                <br />
                                <div class="control-group{% if custom_user_form.password.errors or password_error %} error{% endif %}">
                                    <label class="control-label" for="{{ custom_user_form.password.auto_id }}">Change password to</label>
                                    <div class="controls">
                                        {% if password_error %}<span class="help-inline"><i class="icon-warning-sign" title="Bang"></i> {{ password_error }}</span><br>{% endif %}
                                        {{ custom_user_form.password|htmlattributes:"class:input-large, maxlength:100" }}

                                    </div>
                                </div>
                                <div class="control-group noPrint{% if custom_user_form.password.errors or password_error %} error{% endif %}">
                                    <label class="control-label" for="id_password_verify">Confirm password change</label>
                                    <div class="controls">
                                        {% if password_error %}<span class="help-inline"><i class="icon-warning-sign" title="Bang"></i> {{ password_error }}</span><br>{% endif %}
                                        <input type="password" name="password_verify" id="id_password_verify" class="input-large" maxlength="100"/>
                                        <span id="match_pswd" class=""><br/><i class=""></i> Passwords match</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    <div class="control-group{% if form.office_phone.errors or office_phone_error %} error{% endif %}">
                        <label class="control-label" for="{{ form.office_phone.auto_id }}">Office phone</label>
                        <div class="controls">
                            {% if form.office_phone.errors %}<span class="help-inline"><i class="icon-warning-sign" title="Bang"></i> Phone is required.</span><br>{% endif %}
                            {% if office_phone_error %}<span class="help-inline"><i class="icon-warning-sign" title="Bang"></i> Please enter a valid phone number.</span><br>{% endif %}
                            {{ form.office_phone|htmlattributes:"class:input-medium, placeholder:(___)___-____" }}

                        </div>
                    </div>

                    <div class="control-group">
                        <fieldset>
							<legend class="control-label">Status</legend>
							<div class="controls">
								{{ form.account_status }}
							</div>
						</fieldset>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary noPrint">{% if request.current_url_name == 'create_admin_profile' %}Create Account{% else %}Update Account{% endif %}</button>
                    {{ form.administrative_uuid }}
                    {{ custom_user_form.administrative_user }}
                    <input type="hidden" name="office" id="{{ form.office_auto_id }}" value="{{ request.user.administrative_user.office }}" />
                    {% csrf_token %}
                </fieldset>
            </form>
        </div>
    </section>



{% endblock %}

security/templates/resetPassword.html
{% extends 'base.html' %}

{% load html_attributes %}

{% block title %}Reset Password{% endblock %}
{% block content_highlight %}
    <!-- ======== @Region: #highlighted ======== -->
    <div id="highlighted">
        <div class="container">
            <div class="header">
                <h2 class="page-title">
                    <span>Reset Password</span>
                    <small>A link will be sent to you to reset your password. You have {{ temp_expire }} hours to reset it.</small>
                </h2>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="block">
        <div class="row">
            <div class="col-md-6">
                <div>
                    <form action="" method="POST" role="form">
                        <div class="form-group{% if form.email.errors %} has-error{% endif %}">
                        {% if form.email.errors %}
                            <label class="control-label" for="id_email">
                                <i class="fa fa-exclamation-triangle"></i> Please enter a valid email address.
                            </label><br>
                        {% endif %}
                        <input type="text" class="form-control" name="email" id="id_email"
                               placeholder="Email" value="{{ form.email.value|default_if_none:'' }}"/>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Reset Password</button>
                            <a href="{% url 'security:login' %}">Cancel</a>
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}